export const BRAND_TEXTS = {
  appName: "Recetario",
  footerInstitution: "U.E. Padre Jaime Gagñon",
};

export const CATEGORIAS_FACETAS_LISTA = [
  { id: 'todas', nombre: 'Todas', slug: 'todas' },
  { id: 'desayunos', nombre: 'Desayunos', slug: 'desayunos' },
  { id: 'almuerzos', nombre: 'Almuerzos', slug: 'almuerzos' },
  { id: 'cenas', nombre: 'Cenas', slug: 'cenas' },
  { id: 'postres', nombre: 'Postres', slug: 'postres' },
  { id: 'bebidas', nombre: 'Bebidas', slug: 'bebidas' },
];

export const BUSCADOR_TEXTS = {
  heroHeadingPart1: "Cocina con ",
  heroHeadingItalic: "pasión",
  heroHeadingPart2: ", come con gusto.",
  heroSubtext: "Encuentra tu receta favorita, filtra por ingredientes y calcula las porciones para tus comensales.",
  inputLabel: "¿Qué deseas cocinar hoy?",
  inputPlaceholder: "Buscar por nombre o ingrediente (ej: Tarta, Risotto, chocolate...)",
  clearTitle: "Limpiar búsqueda",
  servingsLabel: "Cantidad de porciones",
  servingsDecreaseTitle: "Disminuir porciones",
  servingsIncreaseTitle: "Aumentar porciones",
  difficultyLabel: "Dificultad",
  difficultyAll: "Todas las dificultades",
  difficultyFacil: "Fácil",
  difficultyMedia: "Media",
  difficultyDificil: "Difícil",
  timeLabel: "Tiempo Máx.",
  timeAny: "Cualquier tiempo",
  time15: "Hasta 15 minutos",
  time30: "Hasta 30 minutos",
  time60: "Hasta 60 minutos",
  orderLabel: "Ordenar por",
  orderRecientes: "Más Recientes",
  orderTiempo: "Menor Tiempo de Prep.",
  orderAlfabetico: "Nombre (A-Z)",
  resultsSingular: "receta encontrada",
  resultsPlural: "recetas encontradas",
  pagePrev: "Anterior",
  pageNext: "Siguiente",
  pagePrevTitle: "Página anterior",
  pageNextTitle: "Página siguiente",
  showingText: "Mostrando",
  pageText: "Página",
  ofText: "de",
};

export const INICIO_TEXTS = {
  heroHeading: "Cocina con pasión, come con gusto.",
  heroSubtext: "Explora e interactúa con tus recetas.",
  searchPlaceholder: "Busca por nombre o ingrediente...",
  btnCatalog: "Ver Catálogo por Categorías",
  titleGrid: "Todas las Recetas",
  noRecipesFound: "No se encontraron recetas",
  tryOtherKeywords: "Intenta con otros ingredientes, palabras clave o cambia de categoría.",
  btnResetFilters: "Restablecer Filtros",
  linkInicio: "Inicio",
  linkCatalog: "Ver Catálogo"
};

export const CATALOG_TEXTS = {
  backBtnText: "Inicio",
  sidebarTitle: "Filtrar por Categoría",
  sidebarTip: "Sugerencia del Catálogo: Puedes marcar varios casilleros a la vez para combinar las categorías.",
  searchPlaceholder: "Buscar recetas...",
  noRecipesFound: "No hay recetas que coincidan con los filtros",
  tryClearingFilters: "Prueba desmarcando algunas categorías o cambiando tu búsqueda",
  btnClearFilters: "Limpiar Filtros",
  btnBack: "Volver",
};

export const RECIPE_TEXTS = {
  backBtnText: "Volver al Inicio",
  ingredientsTitle: "Ingredientes",
  stepsTitle: "Instrucciones",
  servingsLabel: "Cantidad de personas / porciones",
  recipeNameLabel: "Nombre de la Receta",
  btnCalculate: "Calcular Porciones",
  didacticTitle: "Regla de Tres Simple Proporcional",
  didacticExplanation: "Para ajustar las cantidades de la receta base ({base} pers.) a tus porciones deseadas ({desired} pers.), el sistema realiza una regla de tres simple:",
  formulaTitle: "Cantidad Ajustada",
  formulaPartMath: "Cantidad Base × {desired} personas",
  formulaDivider: "{base} personas de la receta base",
  formulaFactorTitle: "Factor de Cambio",
  formulaFactorResult: "{factor}x Proporcional",
  didacticTip: "Toca cada ingrediente para marcarlo como listo. Las cantidades están ajustadas a",
  unitPerson: "persona",
  unitPeople: "personas",
  preparationTip: "Toca cada paso al finalizarlo para llevar el control. Puedes iniciar los temporizadores integrados.",
};

export const ERROR_BOUNDARY_TEXTS = {
  title: "Ha ocurrido un inconveniente",
  description: "Ha ocurrido un error inesperado al cargar la aplicación o al conectar con el servidor Express Backend. Comprueba que el backend esté en ejecución.",
  retryButton: "Reintentar / Recargar Página",
};

export const BACKEND_STATUS_TEXTS = {
  badgeOnline: "En línea",
  badgeWakingUp: "Iniciando servidor...",
  badgeOffline: "Modo local",
  modalTitle: "Estado del Servidor",
  onlineTitle: "Conexión activa con el servicio",
  onlineDetail: "El sistema está conectado correctamente y listo para sincronizar tus recetas.",
  wakingUpTitle: "Conectando con el servidor en la nube...",
  wakingUpDetail: "El servidor en la nube se está iniciando tras un periodo de inactividad. Esto puede tomar entre 30 y 45 segundos.",
  wakingUpAlertTitle: "Inicio automático del servicio",
  wakingUpAlertText: "Para ahorrar recursos en el plan gratuito, el servidor entra en reposo si no hay visitas recientes. Tu solicitud ya lo está despertando.",
  offlineTitle: "Servicio no disponible temporalmente",
  offlineDetail: "No se pudo conectar con el servidor central. La aplicación continuará funcionando con las recetas almacenadas en tu dispositivo.",
  offlineAlertTitle: "Funcionamiento sin conexión",
  offlineAlertText: "Puedes explorar y utilizar el recetario normalmente con los datos de muestra guardados localmente.",
  btnRetry: "Verificar conexión de nuevo",
};

export const RECETA_FORM_TEXTS = {
  titleCreate: "Publicar Nueva Receta",
  titleEdit: "Editar Receta Gastronómica",
  subtitleCreate: "Completa la información para compartir tu platillo con la comunidad",
  subtitleEdit: "Modifica las proporciones, tiempos, ingredientes o instrucciones de tu receta",
  labelTitulo: "Título de la Receta",
  placeholderTitulo: "Ej. Sopa Azteca Tradicional",
  labelDescripcion: "Descripción General",
  placeholderDescripcion: "Describe brevemente el sabor, historia o presentación de tu platillo...",
  labelCategoria: "Categoría",
  selectCategoriaDefault: "Selecciona una categoría",
  labelTiempoPrep: "Tiempo de Preparación (min)",
  labelTiempoCoccion: "Tiempo de Cocción (min)",
  labelPorciones: "Porciones",
  labelDificultad: "Nivel de Dificultad",
  dificultadFacil: "Fácil",
  dificultadMedia: "Media",
  dificultadDificil: "Difícil",
  labelImagenSection: "Fotografía de la Receta",
  tabSubirArchivo: "Galería o Arrastrar",
  tabUrlExterna: "Enlace URL",
  placeholderImagenUrl: "Ingresa la URL pública de la imagen (https://...)",
  dropzoneText: "Haz clic para buscar en tu galería o arrastra una foto aquí",
  dropzoneSubtext: "Formatos permitidos: JPG, PNG o WEBP (Máximo 5 MB)",
  btnCambiarFoto: "Cambiar Foto",
  btnQuitarFoto: "Quitar Foto",
  fotoSeleccionadaBadge: "Fotografía cargada con éxito",
  sectionIngredientesTitle: "Ingredientes de la Receta",
  placeholderIngNombre: "Nombre (Ej. Harina de trigo)",
  placeholderIngCantidad: "Cantidad (Ej. 250 o 1/2)",
  placeholderIngUnidad: "Unidad (Ej. gramos, tazas, cdas)",
  btnAddIngrediente: "Agregar Ingrediente",
  sectionPasosTitle: "Instrucciones de Preparación",
  placeholderPasoInstruccion: "Describe el paso detalladamente...",
  btnAddPaso: "Agregar Paso de Preparación",
  btnSubmitCreate: "Guardar y Publicar Receta",
  btnSubmitEdit: "Guardar Cambios de Receta",
  btnCancel: "Cancelar",
  validationErrorTitle: "Formulario Incompleto",
  validationRequiredFields: "El título y la descripción son obligatorios.",
  validationIngredientes: "Debe incluir al menos un ingrediente completo.",
  validationPasos: "Debe incluir al menos un paso de preparación.",
  toastCreateSuccess: "¡Receta publicada con éxito!",
  toastEditSuccess: "¡Receta actualizada con éxito!",
  toastError: "Error al guardar la receta.",
};

export const FAVORITOS_TEXTS = {
  sectionTitle: "Mis Recetas Favoritas",
  sectionSubtitle: "Tu recetario personal guardado con tus mejores elecciones culinarias.",
  chipLabel: "Mis Favoritos",
  emptyTitle: "Aún no tienes recetas favoritas",
  emptySubtitle: "Guarda las recetas que más te gusten haciendo clic en el corazón para encontrarlas fácilmente aquí.",
  guestTitle: "Inicia Sesión para ver tus Favoritos",
  guestSubtitle: "Crea tu cuenta o ingresa a tu perfil para guardar tus recetas preferidas en la nube y acceder a ellas desde cualquier dispositivo.",
  btnIniciarSesion: "Iniciar Sesión",
  toastAdded: "Receta agregada a tus favoritos",
  toastRemoved: "Receta eliminada de tus favoritos",
  toastError: "No se pudo actualizar tus favoritos. Intenta de nuevo.",
  requiresAuth: "Inicia sesión o regístrate para guardar recetas en tu cuenta",
  loadingFavoritos: "Cargando tus recetas favoritas...",
  btnVerTodos: "Explorar todas las recetas",
};

export const ADMIN_TEXTS = {
  panelTitle: "Panel de Administración y Moderación",
  panelSubtitle: "Gestión global de publicaciones, categorías gastronómicas y roles de usuarios.",
  tabModeracion: "Moderación de Recetas",
  tabCategorias: "Gestión de Categorías",
  tabUsuarios: "Usuarios y Roles",
  badgeAdmin: "Administrador",
  btnPanelAdmin: "Panel Admin",
  colTitulo: "Título de Receta",
  colAutor: "Autor / Chef",
  colCategoria: "Categoría",
  colAcciones: "Acciones",
  colNombre: "Nombre",
  colEmail: "Correo Electrónico",
  colRol: "Rol Actual",
  btnEditar: "Editar",
  btnEliminar: "Eliminar",
  btnModerar: "Moderar / Borrar",
  btnCrearCategoria: "Nueva Categoría",
  btnGuardarCategoria: "Guardar Categoría",
  btnCambiarRol: "Guardar Rol",
  placeholderNombreCat: "Nombre (Ej: Ensaladas)",
  placeholderSlugCat: "Slug opcional (Ej: ensaladas)",
  confirmDeleteRecipe: "¿Estás seguro de eliminar esta receta? Esta acción no se puede deshacer.",
  confirmDeleteCategory: "¿Estás seguro de eliminar esta categoría?",
  toastRoleUpdated: "Rol de usuario actualizado con éxito",
  toastCategoryCreated: "Categoría registrada con éxito",
  toastCategoryUpdated: "Categoría actualizada con éxito",
  toastCategoryDeleted: "Categoría eliminada con éxito",
  toastRecipeDeleted: "Receta eliminada correctamente",
  toastError: "Ocurrió un error al procesar la solicitud de administración.",
  btnClosePanel: "Cerrar Panel",
  btnVer: "Ver",
  tooltipVer: "Vista previa rápida independiente de la pantalla",
  tooltipBorrar: "Eliminar receta por moderación de contenido",
  btnCancelar: "Cancelar",
  placeholderBuscarUsuario: "Buscar usuario por nombre o correo...",
  loadingUsuarios: "Cargando usuarios...",
  modalConfirmModerationTitle: "Confirmar Moderación",
  modalConfirmCategoryTitle: "Eliminar Categoría",
  btnConfirmDelete: "Sí, Eliminar",
  btnIrPaginaCompleta: "Ir a Página Completa",
  btnEliminarEstaReceta: "Eliminar esta Receta",
  titleToastRol: "Rol Actualizado",
  titleToastErrorRol: "Error al Cambiar Rol",
  titleToastCatCreada: "Categoría Registrada",
  titleToastErrorCatCreada: "Error al Crear Categoría",
  titleToastCatActualizada: "Categoría Actualizada",
  titleToastErrorCatActualizada: "Error al Actualizar Categoría",
  titleToastCatEliminada: "Categoría Eliminada",
  titleToastErrorCatEliminada: "Error al Eliminar Categoría",
  titleToastModeracion: "Moderación Completada",
  titleToastErrorModeracion: "Error al Moderar Receta",
  titleToastErrorAdmin: "Error de Administración",
};

export const TRADUCCION_ERRORES = {
  "request entity too large": "La fotografía elegida supera el límite de peso permitido (10 MB). Selecciona una foto de menor tamaño.",
  "network error": "No se pudo conectar con el servidor. Comprueba tu conexión a internet o que el backend esté encendido.",
  "unauthorized": "Su sesión no tiene permisos o ha expirado. Por favor, vuelva a ingresar.",
  "token expired": "Su sesión ha expirado. Por favor, inicie sesión nuevamente.",
  "internal server error": "Ocurrió un inconveniente interno en el servidor. Inténtelo más tarde.",
};

/**
 * Traduce cualquier mensaje técnico o en inglés capturado a español entendible.
 */
export const traducirErrorMensaje = (errMessage) => {
  if (!errMessage) return "Ocurrió un inconveniente inesperado al procesar la solicitud.";
  const msgMin = String(errMessage).toLowerCase();
  for (const [clave, traduccion] of Object.entries(TRADUCCION_ERRORES)) {
    if (msgMin.includes(clave)) return traduccion;
  }
  return errMessage;
};
