export const BRAND_TEXTS = {
  appName: "Recetario",
  footerInstitution: "U.E. Padre Jaime Gagñon",
};

export const INICIO_TEXTS = {
  heroHeading: "Cocina con pasión, come con gusto.",
  heroSubtext: "Explora e interactúa con tus recetas.",
  searchPlaceholder: "Busca por nombre o ingrediente...",
  btnCatalog: "Ver Catálogo por Categorías",
  titleGrid: "Todas las Recetas",
  noRecipesFound: "No se encontraron recetas",
  tryOtherKeywords: "Intenta con otros ingredientes, palabras clave o cambia de categoría.",
  btnResetFilters: "Restablecer Filtros",
  linkInicio: "Inicio",
  linkCatalog: "Ver Catálogo"
};

export const CATALOG_TEXTS = {
  backBtnText: "Inicio",
  sidebarTitle: "Filtrar por Categoría",
  sidebarTip: "Sugerencia del Catálogo: Puedes marcar varios casilleros a la vez para combinar las categorías.",
  searchPlaceholder: "Buscar recetas...",
  noRecipesFound: "No hay recetas que coincidan con los filtros",
  tryClearingFilters: "Prueba desmarcando algunas categorías o cambiando tu búsqueda",
  btnClearFilters: "Limpiar Filtros",
  btnBack: "Volver",
};

export const RECIPE_TEXTS = {
  backBtnText: "Volver al Inicio",
  ingredientsTitle: "Ingredientes",
  stepsTitle: "Instrucciones",
  servingsLabel: "Cantidad de personas / porciones",
  recipeNameLabel: "Nombre de la Receta",
  btnCalculate: "Calcular Porciones",
  didacticTitle: "Regla de Tres Simple Proporcional",
  didacticExplanation: "Para ajustar las cantidades de la receta base ({base} pers.) a tus porciones deseadas ({desired} pers.), el sistema realiza una regla de tres simple:",
  formulaTitle: "Cantidad Ajustada",
  formulaPartMath: "Cantidad Base × {desired} personas",
  formulaDivider: "{base} personas de la receta base",
  formulaFactorTitle: "Factor de Cambio",
  formulaFactorResult: "{factor}x Proporcional",
  didacticTip: "Toca cada ingrediente para marcarlo como listo. Las cantidades están ajustadas a",
  unitPerson: "persona",
  unitPeople: "personas",
  preparationTip: "Toca cada paso al finalizarlo para llevar el control. Puedes iniciar los temporizadores integrados.",
};

export const ERROR_BOUNDARY_TEXTS = {
  title: "Ha ocurrido un inconveniente",
  description: "Ha ocurrido un error inesperado al cargar la aplicación o al conectar con el servidor Express Backend. Comprueba que el backend esté en ejecución.",
  retryButton: "Reintentar / Recargar Página",
};

export const BACKEND_STATUS_TEXTS = {
  badgeOnline: "En línea",
  badgeWakingUp: "Iniciando servidor...",
  badgeOffline: "Modo local",
  modalTitle: "Estado del Servidor",
  onlineTitle: "Conexión activa con el servicio",
  onlineDetail: "El sistema está conectado correctamente y listo para sincronizar tus recetas.",
  wakingUpTitle: "Conectando con el servidor en la nube...",
  wakingUpDetail: "El servidor en la nube se está iniciando tras un periodo de inactividad. Esto puede tomar entre 30 y 45 segundos.",
  wakingUpAlertTitle: "Inicio automático del servicio",
  wakingUpAlertText: "Para ahorrar recursos en el plan gratuito, el servidor entra en reposo si no hay visitas recientes. Tu solicitud ya lo está despertando.",
  offlineTitle: "Servicio no disponible temporalmente",
  offlineDetail: "No se pudo conectar con el servidor central. La aplicación continuará funcionando con las recetas almacenadas en tu dispositivo.",
  offlineAlertTitle: "Funcionamiento sin conexión",
  offlineAlertText: "Puedes explorar y utilizar el recetario normalmente con los datos de muestra guardados localmente.",
  btnRetry: "Verificar conexión de nuevo",
};

export const RECETA_FORM_TEXTS = {
  titleCreate: "Publicar Nueva Receta",
  titleEdit: "Editar Receta Gastronómica",
  subtitleCreate: "Completa la información para compartir tu platillo con la comunidad",
  subtitleEdit: "Modifica las proporciones, tiempos, ingredientes o instrucciones de tu receta",
  labelTitulo: "Título de la Receta",
  placeholderTitulo: "Ej. Sopa Azteca Tradicional",
  labelDescripcion: "Descripción General",
  placeholderDescripcion: "Describe brevemente el sabor, historia o presentación de tu platillo...",
  labelCategoria: "Categoría",
  selectCategoriaDefault: "Selecciona una categoría",
  labelTiempoPrep: "Tiempo de Preparación (min)",
  labelTiempoCoccion: "Tiempo de Cocción (min)",
  labelPorciones: "Porciones",
  labelDificultad: "Nivel de Dificultad",
  dificultadFacil: "Fácil",
  dificultadMedia: "Media",
  dificultadDificil: "Difícil",
  labelImagenUrl: "Fotografía de la Receta",
  placeholderImagenUrl: "O pega una URL externa (https://...)",
  dropzoneText: "Haz clic para buscar en tu galería o arrastra una imagen aquí",
  dropzoneSubtext: "Soporta JPG, PNG y WEBP (Máx 5 MB)",
  btnCambiarFoto: "Cambiar / Eliminar Foto",
  sectionIngredientesTitle: "Ingredientes de la Receta",
  placeholderIngNombre: "Nombre (Ej. Harina de trigo)",
  placeholderIngCantidad: "Cantidad (Ej. 250 o 1/2)",
  placeholderIngUnidad: "Unidad (Ej. gramos, tazas, cdas)",
  btnAddIngrediente: "Agregar Ingrediente",
  sectionPasosTitle: "Instrucciones de Preparación",
  placeholderPasoInstruccion: "Describe el paso detalladamente...",
  btnAddPaso: "Agregar Paso de Preparación",
  btnSubmitCreate: "Guardar y Publicar Receta",
  btnSubmitEdit: "Guardar Cambios de Receta",
  btnCancel: "Cancelar",
  validationErrorTitle: "Formulario Incompleto",
  validationRequiredFields: "El título y la descripción son obligatorios.",
  validationIngredientes: "Debe incluir al menos un ingrediente completo.",
  validationPasos: "Debe incluir al menos un paso de preparación.",
  toastCreateSuccess: "¡Receta publicada con éxito!",
  toastEditSuccess: "¡Receta actualizada con éxito!",
  toastError: "Error al guardar la receta.",
};
